import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { useTheme } from '@local_modules/theme'
import { Theme } from 'App.theme'
import { Div, P, Button } from '@local_modules/tags'
import { A, Header } from '@local_modules/router'

const Home: NextPage = () => {

  const { color, fontSize, shadow } = useTheme<Theme>();
  
  return (
    <Div>
      <Head>
        <title>Devmonster's react-modules</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Div>
        <Div style={{ padding: 20 }}>
          <P style={{ 
            fontSize: fontSize.x2l, 
            marginBottom: 20 
            }}>Devmonster's react-modules!!</P>
          <Div>
            <A href={'/themeEx'}>
              <Button 
                color={color.primary}
                style={{ marginBottom: 8 }}>
                react-theme
              </Button>
            </A>
            <A href={'/tagsEx'}>
              <Button 
                color={color.primary}
                style={{ marginBottom: 8 }}>
                react-tags
              </Button>
            </A>
            <A href={'/routerEx'}>
              <Button 
                color={color.primary}>
                react-router
              </Button>
            </A>
          </Div>
        </Div>
      </Div>
    </Div>
  )
}

export default Home
