import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { useTheme } from '@local_modules/theme'
import { Theme } from 'App.theme'
import { Div, P, Button } from '@local_modules/tags'

const Home: NextPage = () => {

  const { color, fontSize, shadow } = useTheme<Theme>();
  
  return (
    <Div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Div style={{ backgroundColor: color.white, flex: 1 }}>
        <Div style={{ padding: 20 }}>
          <P style={{ 
            fontSize: fontSize.x2l, 
            marginBottom: 20 
            }}>React-native-modules!!</P>
          <Div>
            <Link href={'/themeEx'}>
              <Button 
                color={color.primary}
                style={{ marginBottom: 8 }}>
                react-native-theme
              </Button>
            </Link>
            <Link href={'/tagsEx'}>
              <Button 
                color={color.primary}>
                react-native-tags
              </Button>
            </Link>
          </Div>
        </Div>
      </Div>
    </Div>
  )
}

export default Home
