import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { useTheme } from '@local_modules/theme/src'
import { Theme } from 'App.theme'

const Home: NextPage = () => {

  const { color } = useTheme<Theme>();
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ backgroundColor: color.white, flex: 1 }}>
        <div style={{ padding: 20 }}>
          <Link href={`/themeEx`}>
            <button>Theme</button>
          </Link>
        </div>
      </div>
    </div>
  )
}

export default Home
